language: ruby
sudo: false

cache:
  bundler: true

services:
  - redis
  - postgresql

before_script:
  - cp config/database.travis.yml config/database.yml

rvm:
  - 2.4.0

script:
  - bundle exec rake db:setup
  - bundle exec rake spec
  - bundle exec rake test