language: ruby
sudo: false

cache:
  bundler: true

services:
  - redis
  - postgresql

addons:
  postgresql: "9.6"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml

rvm:
  - 2.4.0

script:
  - bundle exec rake db:setup
  - bundle exec rake spec
  - bundle exec rake test